### ISSUE TITLE
Open readme.ipynb automatically at startup when login in notebook

### ISSUE THREAD

**Issue by pattdepanick** [Workshops-on-Demand/wod-backend#8]
readmefirst notebook should open up automatically when students logs in.

**Comment by bcornec** [comment]
At https://jupyterhub.readthedocs.io/en/latest/getting-started/spawners-basics.html they indicate that "Since the single-user server extends the notebook server application, it still loads configuration from the jupyter_notebook_config.py config file. Each user may have one of these files in $HOME/.jupyter/"

And at https://jupyter-notebook.readthedocs.io/en/stable/config_overview.html they mention that "To create a jupyter_notebook_config.py file in the .jupyter directory, with all the defaults commented out, use the following command:

    $ jupyter notebook --generate-config"

And also at https://jupyterhub.readthedocs.io/en/latest/getting-started/spawners-basics.html they mention that "This could be used to set the user’s default page for the single-user server:

c.Spawner.args = ['--NotebookApp.default_url=/notebooks/Welcome.ipynb']"


So I think we could use that mechanism to generate an empty config file for the user at build time, amend the file with c.NotebookApp.custom_display_url = 'WKSHP-*/0-...'
That would avoid the cumbersome file in workspaces which seems to work randomly (no doc found on that one :-()

I propose we make a try next time we work on this.

**Comment by pattdepanick** [comment]
temporary issue following 
https://discourse.jupyter.org/t/jupyterlab-settings-dir-defaults-to-jupyterhub-root-directory/17103

Config.py modification : 
c.Spawner.environment = {'JUPYTERLAB_SETTINGS_DIR': lambda spawner: '/home/' + spawner.user.name + '/.jupyter'}
